guild_id: "1319134874094800896"
bot_token: "MTMyMzc0MzMwOTAzODA5MjM1MA.GYiYfK.NMMevV-JBMnzLMzZTjsF0ZFE8bbQXffBenl_iM"
joins_channel_id: "1320499565270401044"
reviews-channel_id: "1323771307808129125"

join-member:
  message: "↪ {user-mention}"
  author: "¡BIENVENIDO A MI SERVIDOR!"
  title: "¡Bienvenido {user-name}!"
  description: |
    ¡Estás en nuestra nueva comunidad, puedes entrar a nuestro servidor y conseguir nuevos amigos!
    
    Recuerda seguir las reglas <#Canal Reglas>.
    
    > **Información general del servidor:**
      
    • **Tienda**: Próximamente
    • **IP**: Próximamente
  footer: "Copyright © 2024 | Mi Servidor"
  color: "#00FF00"